use anyhow::{anyhow, Context, Result};
use cnc_geom::Vec3;
use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::Path;

use crate::{MoveKind, Toolpath};

const EPSILON: f64 = 1e-9;

#[derive(Debug, Clone, Copy)]
pub struct ObjExportOptions {
    pub radius: f64,
    pub radial_sides: u32,
    pub include_caps: bool,
    pub feed_color_rgb: (f32, f32, f32),
}

impl Default for ObjExportOptions {
    fn default() -> Self {
        Self {
            radius: 0.4,
            radial_sides: 12,
            include_caps: true,
            feed_color_rgb: (0.35, 0.65, 0.95),
        }
    }
}

pub fn export_toolpath_obj(
    toolpath: &Toolpath,
    obj_path: &Path,
    options: &ObjExportOptions,
) -> Result<()> {
    validate_options(options)?;

    let mut mesh = Mesh::default();
    let mut exported_segments = 0usize;
    for segment in &toolpath.segments {
        if !matches!(segment.kind, MoveKind::Feed) {
            continue;
        }
        if add_segment_tube(&mut mesh, segment.start, segment.end, options) {
            exported_segments += 1;
        }
    }

    if exported_segments == 0 || mesh.faces.is_empty() {
        return Err(anyhow!("no feed segments to export"));
    }

    if let Some(parent) = obj_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).with_context(|| {
                format!("failed to create output directory: {}", parent.display())
            })?;
        }
    }

    let mtl_path = obj_path.with_extension("mtl");
    write_obj(obj_path, &mtl_path, &mesh)?;
    write_mtl(&mtl_path, options.feed_color_rgb)?;
    Ok(())
}

fn validate_options(options: &ObjExportOptions) -> Result<()> {
    if !options.radius.is_finite() || options.radius <= 0.0 {
        return Err(anyhow!("export radius must be a positive finite value"));
    }
    if options.radial_sides < 3 {
        return Err(anyhow!("export sides must be >= 3"));
    }
    Ok(())
}

#[derive(Default)]
struct Mesh {
    vertices: Vec<Vec3>,
    faces: Vec<[usize; 3]>,
}

impl Mesh {
    fn push_vertex(&mut self, point: Vec3) -> usize {
        self.vertices.push(point);
        self.vertices.len()
    }

    fn push_face(&mut self, a: usize, b: usize, c: usize) {
        self.faces.push([a, b, c]);
    }
}

fn add_segment_tube(mesh: &mut Mesh, start: Vec3, end: Vec3, options: &ObjExportOptions) -> bool {
    let axis = end - start;
    let axis_len = length(axis);
    if axis_len <= EPSILON {
        return false;
    }

    let axis_dir = axis * (1.0 / axis_len);
    let mut reference = if axis_dir.z.abs() < 0.9 {
        Vec3::new(0.0, 0.0, 1.0)
    } else {
        Vec3::new(1.0, 0.0, 0.0)
    };
    let mut tangent = normalize(cross(axis_dir, reference));
    if tangent.is_none() {
        reference = Vec3::new(0.0, 1.0, 0.0);
        tangent = normalize(cross(axis_dir, reference));
    }
    let Some(tangent) = tangent else {
        return false;
    };
    let Some(bitangent) = normalize(cross(axis_dir, tangent)) else {
        return false;
    };

    let radial_sides = options.radial_sides as usize;
    let mut start_ring = Vec::with_capacity(radial_sides);
    let mut end_ring = Vec::with_capacity(radial_sides);
    for i in 0..radial_sides {
        let angle = std::f64::consts::TAU * (i as f64 / radial_sides as f64);
        let radial =
            tangent * (angle.cos() * options.radius) + bitangent * (angle.sin() * options.radius);
        start_ring.push(mesh.push_vertex(start + radial));
        end_ring.push(mesh.push_vertex(end + radial));
    }

    for i in 0..radial_sides {
        let next = (i + 1) % radial_sides;
        let s0 = start_ring[i];
        let s1 = start_ring[next];
        let e0 = end_ring[i];
        let e1 = end_ring[next];
        mesh.push_face(s0, e0, e1);
        mesh.push_face(s0, e1, s1);
    }

    if options.include_caps {
        let start_center = mesh.push_vertex(start);
        let end_center = mesh.push_vertex(end);
        for i in 0..radial_sides {
            let next = (i + 1) % radial_sides;
            mesh.push_face(start_center, start_ring[next], start_ring[i]);
            mesh.push_face(end_center, end_ring[i], end_ring[next]);
        }
    }

    true
}

fn write_obj(path: &Path, mtl_path: &Path, mesh: &Mesh) -> Result<()> {
    let file = File::create(path)
        .with_context(|| format!("failed to create obj file: {}", path.display()))?;
    let mut writer = BufWriter::new(file);
    let mtl_name = mtl_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("material.mtl");

    writeln!(writer, "# generated by cnc-view-tui")?;
    writeln!(writer, "mtllib {}", mtl_name)?;
    writeln!(writer, "o toolpath")?;
    writeln!(writer, "usemtl feed_path")?;
    for vertex in &mesh.vertices {
        writeln!(writer, "v {:.6} {:.6} {:.6}", vertex.x, vertex.y, vertex.z)?;
    }
    for face in &mesh.faces {
        writeln!(writer, "f {} {} {}", face[0], face[1], face[2])?;
    }
    writer.flush()?;
    Ok(())
}

fn write_mtl(path: &Path, color: (f32, f32, f32)) -> Result<()> {
    let file = File::create(path)
        .with_context(|| format!("failed to create mtl file: {}", path.display()))?;
    let mut writer = BufWriter::new(file);
    let (r, g, b) = (
        color.0.clamp(0.0, 1.0),
        color.1.clamp(0.0, 1.0),
        color.2.clamp(0.0, 1.0),
    );
    writeln!(writer, "newmtl feed_path")?;
    writeln!(writer, "Ka 0.100000 0.100000 0.100000")?;
    writeln!(writer, "Kd {:.6} {:.6} {:.6}", r, g, b)?;
    writeln!(writer, "Ks 0.150000 0.150000 0.150000")?;
    writeln!(writer, "Ns 64.000000")?;
    writer.flush()?;
    Ok(())
}

fn cross(a: Vec3, b: Vec3) -> Vec3 {
    Vec3::new(
        a.y * b.z - a.z * b.y,
        a.z * b.x - a.x * b.z,
        a.x * b.y - a.y * b.x,
    )
}

fn length(v: Vec3) -> f64 {
    (v.x * v.x + v.y * v.y + v.z * v.z).sqrt()
}

fn normalize(v: Vec3) -> Option<Vec3> {
    let len = length(v);
    if len <= EPSILON {
        return None;
    }
    Some(v * (1.0 / len))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{LineSegment, MoveKind, Toolpath, ToolpathStats};
    use cnc_geom::{Bounds3, Vec3};
    use std::path::PathBuf;

    fn test_toolpath(segments: Vec<LineSegment>) -> Toolpath {
        let mut bounds = Bounds3::new();
        for segment in &segments {
            bounds.include(segment.start);
            bounds.include(segment.end);
        }
        Toolpath {
            segments,
            bounds,
            stats: ToolpathStats::default(),
            line_segment_ends: Vec::new(),
        }
    }

    fn unique_temp_obj_path(name: &str) -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let mut dir = std::env::temp_dir();
        dir.push(format!(
            "cnc_gcode_obj_export_{}_{}_{}",
            name,
            std::process::id(),
            nanos
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir.join("toolpath.obj")
    }

    #[test]
    fn rejects_invalid_options() {
        let path = unique_temp_obj_path("invalid_options");
        let toolpath = test_toolpath(vec![LineSegment {
            start: Vec3::new(0.0, 0.0, 0.0),
            end: Vec3::new(1.0, 0.0, 0.0),
            kind: MoveKind::Feed,
        }]);

        let invalid_radius = ObjExportOptions {
            radius: 0.0,
            ..ObjExportOptions::default()
        };
        let err = export_toolpath_obj(&toolpath, &path, &invalid_radius).unwrap_err();
        assert!(err.to_string().contains("radius"));

        let invalid_sides = ObjExportOptions {
            radial_sides: 2,
            ..ObjExportOptions::default()
        };
        let err = export_toolpath_obj(&toolpath, &path, &invalid_sides).unwrap_err();
        assert!(err.to_string().contains("sides"));
    }

    #[test]
    fn skips_rapid_segments() {
        let path = unique_temp_obj_path("rapid_only");
        let toolpath = test_toolpath(vec![LineSegment {
            start: Vec3::new(0.0, 0.0, 0.0),
            end: Vec3::new(2.0, 0.0, 0.0),
            kind: MoveKind::Rapid,
        }]);

        let err = export_toolpath_obj(&toolpath, &path, &ObjExportOptions::default()).unwrap_err();
        assert!(err.to_string().contains("no feed segments"));
    }

    #[test]
    fn exports_obj_for_feed_segment() {
        let path = unique_temp_obj_path("feed_segment");
        let toolpath = test_toolpath(vec![LineSegment {
            start: Vec3::new(0.0, 0.0, 0.0),
            end: Vec3::new(0.0, 0.0, 5.0),
            kind: MoveKind::Feed,
        }]);

        export_toolpath_obj(&toolpath, &path, &ObjExportOptions::default()).unwrap();
        let obj = std::fs::read_to_string(&path).unwrap();
        let mtl = std::fs::read_to_string(path.with_extension("mtl")).unwrap();

        assert!(obj.lines().any(|line| line.starts_with("v ")));
        assert!(obj.lines().any(|line| line.starts_with("f ")));
        assert!(obj.contains("mtllib"));
        assert!(obj.contains("usemtl feed_path"));
        assert!(!obj.to_ascii_lowercase().contains("nan"));
        assert!(mtl.contains("newmtl feed_path"));
    }
}
